# tensor axes

In [1]:
# OD tensor
import numpy as np
x = np.array(12)

In [2]:
x

array(12)

In [4]:
# a scalar is a tensor with 0 axes
x.ndim

0

In [5]:
# vector = 1D tensor
x = np.array([12,13,15])
x.ndim

1

In [7]:
# 1D tensor has 3 dimensions
len(x)

3

In [8]:
# matrices = 2D tensor
x = np.array([
    [5,6,4,8,9],
    [23,98,674,2,7],
    [46,89,3,31,5]
])

x.ndim

2

In [9]:
x.shape

(3, 5)

In [10]:
# 3D tensor

x = np.array([
    [
        [65,45,64],
        [1,2,3]
    ],
    [
        [66,88,99],
        [54,6,7]
    ],
    [
        [5,6,4],
        [5,6,7]
    ]

])
x.ndim

3

In [11]:
x.shape

(3, 2, 3)

In [12]:
x

array([[[65, 45, 64],
        [ 1,  2,  3]],

       [[66, 88, 99],
        [54,  6,  7]],

       [[ 5,  6,  4],
        [ 5,  6,  7]]])

In [18]:
# 4D tensor
y  = np.array([x,x*2])
y.ndim

4

In [19]:
y.shape

(2, 3, 2, 3)

In [20]:
y

array([[[[ 65,  45,  64],
         [  1,   2,   3]],

        [[ 66,  88,  99],
         [ 54,   6,   7]],

        [[  5,   6,   4],
         [  5,   6,   7]]],


       [[[130,  90, 128],
         [  2,   4,   6]],

        [[132, 176, 198],
         [108,  12,  14]],

        [[ 10,  12,   8],
         [ 10,  12,  14]]]])

In [21]:
# 5D tensor
z = np.array([y, y/2])
z.ndim

5

In [22]:
z.shape

(2, 2, 3, 2, 3)

In [23]:
z

array([[[[[  65. ,   45. ,   64. ],
          [   1. ,    2. ,    3. ]],

         [[  66. ,   88. ,   99. ],
          [  54. ,    6. ,    7. ]],

         [[   5. ,    6. ,    4. ],
          [   5. ,    6. ,    7. ]]],


        [[[ 130. ,   90. ,  128. ],
          [   2. ,    4. ,    6. ]],

         [[ 132. ,  176. ,  198. ],
          [ 108. ,   12. ,   14. ]],

         [[  10. ,   12. ,    8. ],
          [  10. ,   12. ,   14. ]]]],



       [[[[  32.5,   22.5,   32. ],
          [   0.5,    1. ,    1.5]],

         [[  33. ,   44. ,   49.5],
          [  27. ,    3. ,    3.5]],

         [[   2.5,    3. ,    2. ],
          [   2.5,    3. ,    3.5]]],


        [[[  65. ,   45. ,   64. ],
          [   1. ,    2. ,    3. ]],

         [[  66. ,   88. ,   99. ],
          [  54. ,    6. ,    7. ]],

         [[   5. ,    6. ,    4. ],
          [   5. ,    6. ,    7. ]]]]])

In [24]:
z.dtype

dtype('float64')

In [25]:
x.dtype

dtype('int64')

In [26]:
y.dtype

dtype('int64')

## Slicing tensors

In [29]:
z[:1].shape

(1, 2, 3, 2, 3)

In [30]:
z.shape

(2, 2, 3, 2, 3)

In [31]:
z[:,:,:1].shape

(2, 2, 1, 2, 3)

In [33]:
z[:,:,:,:,:1].shape

(2, 2, 3, 2, 1)

In [35]:
z[:,:,:,:,-1:]

array([[[[[  64. ],
          [   3. ]],

         [[  99. ],
          [   7. ]],

         [[   4. ],
          [   7. ]]],


        [[[ 128. ],
          [   6. ]],

         [[ 198. ],
          [  14. ]],

         [[   8. ],
          [  14. ]]]],



       [[[[  32. ],
          [   1.5]],

         [[  49.5],
          [   3.5]],

         [[   2. ],
          [   3.5]]],


        [[[  64. ],
          [   3. ]],

         [[  99. ],
          [   7. ]],

         [[   4. ],
          [   7. ]]]]])

In [41]:
# first sample batch
z[0]

array([[[[  65.,   45.,   64.],
         [   1.,    2.,    3.]],

        [[  66.,   88.,   99.],
         [  54.,    6.,    7.]],

        [[   5.,    6.,    4.],
         [   5.,    6.,    7.]]],


       [[[ 130.,   90.,  128.],
         [   2.,    4.,    6.]],

        [[ 132.,  176.,  198.],
         [ 108.,   12.,   14.]],

        [[  10.,   12.,    8.],
         [  10.,   12.,   14.]]]])

In [42]:
# second sample batch
z[1]

array([[[[ 32.5,  22.5,  32. ],
         [  0.5,   1. ,   1.5]],

        [[ 33. ,  44. ,  49.5],
         [ 27. ,   3. ,   3.5]],

        [[  2.5,   3. ,   2. ],
         [  2.5,   3. ,   3.5]]],


       [[[ 65. ,  45. ,  64. ],
         [  1. ,   2. ,   3. ]],

        [[ 66. ,  88. ,  99. ],
         [ 54. ,   6. ,   7. ]],

        [[  5. ,   6. ,   4. ],
         [  5. ,   6. ,   7. ]]]])

# Operations

In [43]:
x

array([[[65, 45, 64],
        [ 1,  2,  3]],

       [[66, 88, 99],
        [54,  6,  7]],

       [[ 5,  6,  4],
        [ 5,  6,  7]]])

In [49]:
x.shape

(3, 2, 3)

In [51]:
W = np.array([2,2,2])
W.shape

(3,)

In [53]:
Wx = np.dot(x,W)
Wx

array([[348,  12],
       [506, 134],
       [ 30,  36]])

In [54]:
Wx.shape

(3, 2)

In [60]:
np.dot(x,np.array([[1,2], [1,2], [1,2]]))

array([[[174, 348],
        [  6,  12]],

       [[253, 506],
        [ 67, 134]],

       [[ 15,  30],
        [ 18,  36]]])

In [61]:
# broadcasting
x

array([[[65, 45, 64],
        [ 1,  2,  3]],

       [[66, 88, 99],
        [54,  6,  7]],

       [[ 5,  6,  4],
        [ 5,  6,  7]]])

In [62]:
x + np.array([10])

array([[[ 75,  55,  74],
        [ 11,  12,  13]],

       [[ 76,  98, 109],
        [ 64,  16,  17]],

       [[ 15,  16,  14],
        [ 15,  16,  17]]])

# Dot product

In [73]:
def naive_dot(x,y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape[0] == y.shape[0]
    
    z = 0.0
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z

In [66]:
x = np.array([1,1,1])
x.shape

(3,)

In [67]:
x.shape[0]

3

In [70]:
x

array([1, 1, 1])

In [68]:
len(x.shape)

1

In [75]:
y = x * 2
y

array([2, 2, 2])

In [76]:
y.shape

(3,)

In [77]:
naive_dot(x,y)

6.0

In [78]:
# matrix_vector dot
def matrix_vector_dot(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    
    z = np.zeros_like(y)
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[j] += x[i,j] * y[j]
    return z

In [81]:
x = np.array([
    [1,1,1],
    [1,1,1]
])
y = np.array([2,2,2])

In [82]:
matrix_vector_dot(x,y)

array([4, 4, 4])

In [83]:
# 3D . 1D = 2D
x = np.array([
    [
        [1,1,1]
    ],
    [
        [1,1,1]
    ]
        
])


In [84]:
x.shape

(2, 1, 3)

In [85]:
y.shape

(3,)

In [87]:
z = np.dot(x,y)
z

array([[6],
       [6]])

In [88]:
z.shape

(2, 1)

In [89]:
x.T.shape

(3, 1, 2)